"""empty message

Revision ID: e7f440dbb6d9
Revises: 31f047f73406
Create Date: 2024-03-03 17:06:59.382750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f440dbb6d9'
down_revision = '31f047f73406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('people_homeworld_id_fkey', 'planets', ['homeworld_id'], ['id'])

    # ### end Alembic commands ###
